// Auto-generated by generate_mock_data.py using src/ingestion/generator.py
// Re-run: python webapp/generate_mock_data.py

export const mockSummaryKPIs = {
    "status": "success",
    "data": {
        "total_revenue": 318467.78,
        "active_users": 49,
        "total_orders": 200
    }
};

export const mockCLVData = {
    "status": "success",
    "count": 10,
    "data": [
        {
            "user_id": "USR_0011",
            "customer_name": "Julie Porter",
            "customer_city": "Austin",
            "purchase_count": 11,
            "total_spend": 16505.71,
            "avg_order_value": 1500.52,
            "customer_lifespan_days": 28,
            "estimated_clv": 16505.71
        },
        {
            "user_id": "USR_0039",
            "customer_name": "Jennifer Morales",
            "customer_city": "Phoenix",
            "purchase_count": 7,
            "total_spend": 14047.38,
            "avg_order_value": 2006.77,
            "customer_lifespan_days": 27,
            "estimated_clv": 14047.38
        },
        {
            "user_id": "USR_0037",
            "customer_name": "Daniel Wright",
            "customer_city": "Chicago",
            "purchase_count": 9,
            "total_spend": 13951.95,
            "avg_order_value": 1550.22,
            "customer_lifespan_days": 23,
            "estimated_clv": 13951.95
        },
        {
            "user_id": "USR_0020",
            "customer_name": "Joyce Berry",
            "customer_city": "San Jose",
            "purchase_count": 8,
            "total_spend": 12907.8,
            "avg_order_value": 1613.48,
            "customer_lifespan_days": 21,
            "estimated_clv": 12907.8
        },
        {
            "user_id": "USR_0033",
            "customer_name": "Anthony Hoffman",
            "customer_city": "Jacksonville",
            "purchase_count": 7,
            "total_spend": 11563.18,
            "avg_order_value": 1651.88,
            "customer_lifespan_days": 22,
            "estimated_clv": 11563.18
        },
        {
            "user_id": "USR_0036",
            "customer_name": "Michael Suarez",
            "customer_city": "Phoenix",
            "purchase_count": 6,
            "total_spend": 11135.51,
            "avg_order_value": 1855.92,
            "customer_lifespan_days": 21,
            "estimated_clv": 11135.51
        },
        {
            "user_id": "USR_0003",
            "customer_name": "Erin Gonzalez",
            "customer_city": "San Antonio",
            "purchase_count": 5,
            "total_spend": 11037.8,
            "avg_order_value": 2207.56,
            "customer_lifespan_days": 16,
            "estimated_clv": 11037.8
        },
        {
            "user_id": "USR_0040",
            "customer_name": "Ryan Gay",
            "customer_city": "Austin",
            "purchase_count": 7,
            "total_spend": 10995.62,
            "avg_order_value": 1570.8,
            "customer_lifespan_days": 29,
            "estimated_clv": 10995.62
        },
        {
            "user_id": "USR_0027",
            "customer_name": "Stacey Daniel",
            "customer_city": "Los Angeles",
            "purchase_count": 7,
            "total_spend": 10779.88,
            "avg_order_value": 1539.98,
            "customer_lifespan_days": 28,
            "estimated_clv": 10779.88
        },
        {
            "user_id": "USR_0021",
            "customer_name": "Jeffrey Mitchell",
            "customer_city": "Dallas",
            "purchase_count": 6,
            "total_spend": 9961.78,
            "avg_order_value": 1660.3,
            "customer_lifespan_days": 20,
            "estimated_clv": 9961.78
        }
    ]
};

export const mockMarketBasketData = {
    "status": "success",
    "count": 10,
    "data": [
        {
            "product_a_name": "Jump Rope",
            "product_b_name": "Honey",
            "times_bought_together": 7,
            "product_a": 25,
            "product_b": 28
        },
        {
            "product_a_name": "Laptop Stand",
            "product_b_name": "Basketball",
            "times_bought_together": 6,
            "product_a": 21,
            "product_b": 30
        },
        {
            "product_a_name": "Running Shoes",
            "product_b_name": "Desk Organizer",
            "times_bought_together": 6,
            "product_a": 2,
            "product_b": 29
        },
        {
            "product_a_name": "Winter Jacket",
            "product_b_name": "Jump Rope",
            "times_bought_together": 6,
            "product_a": 17,
            "product_b": 25
        },
        {
            "product_a_name": "Cotton T-Shirt",
            "product_b_name": "Scented Candle",
            "times_bought_together": 5,
            "product_a": 7,
            "product_b": 19
        },
        {
            "product_a_name": "Winter Jacket",
            "product_b_name": "Scented Candle",
            "times_bought_together": 5,
            "product_a": 17,
            "product_b": 19
        },
        {
            "product_a_name": "Green Tea",
            "product_b_name": "Basketball",
            "times_bought_together": 5,
            "product_a": 18,
            "product_b": 30
        },
        {
            "product_a_name": "Organic Milk",
            "product_b_name": "Protein Bars",
            "times_bought_together": 5,
            "product_a": 3,
            "product_b": 8
        },
        {
            "product_a_name": "Wall Clock",
            "product_b_name": "Resistance Bands",
            "times_bought_together": 5,
            "product_a": 14,
            "product_b": 15
        },
        {
            "product_a_name": "Throw Pillow",
            "product_b_name": "Scented Candle",
            "times_bought_together": 5,
            "product_a": 9,
            "product_b": 19
        }
    ]
};
